server:
  port: 9020

swagger:
  api:
    version: @project.version@

info:
  build:
    groupId: @project.groupId@
    artifact: @project.artifactId@
    description: @project.description@
    version: @project.version@
    git:
      branch: @git.branch@
      commit:
        id: @git.commit.id@
        time: @git.commit.time@
        message: '@git.commit.message.short@'